# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 05:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Poi',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default='', srid=4326),
        ),
    ]
