# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 09:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_house_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmpoints',
            name='Lat',
        ),
        migrations.RemoveField(
            model_name='farmpoints',
            name='Lon',
        ),
        migrations.RemoveField(
            model_name='house',
            name='Lat',
        ),
        migrations.RemoveField(
            model_name='house',
            name='Lon',
        ),
        migrations.RemoveField(
            model_name='publicplaces',
            name='Lat',
        ),
        migrations.RemoveField(
            model_name='publicplaces',
            name='Lon',
        ),
        migrations.RemoveField(
            model_name='wells',
            name='Lat',
        ),
        migrations.RemoveField(
            model_name='wells',
            name='Lon',
        ),
        migrations.AddField(
            model_name='farmpoints',
            name='Polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(default='', srid=4326),
        ),
        migrations.AddField(
            model_name='publicplaces',
            name='Poi',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
        ),
        migrations.AddField(
            model_name='wells',
            name='Poi',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
        ),
        migrations.AlterField(
            model_name='house',
            name='Poi',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
        ),
    ]
