# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20171006_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='Audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='members',
            name='Photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
