# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20171006_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Village',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='wells',
            name='Village',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicplaces',
            name='Village',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
