# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20171007_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wells',
            name='Photo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
